### ISSUE TITLE
Question: K8S HA setup

### ISSUE THREAD

**Issue by cmonty14** [geerlingguy/turing-pi-cluster#33]
Hi,

is my understanding correct that Turing Pi Cluster defines only a single master node, and therefore this solution disqualifies for a HA setup of K8S.
Is this correct?

Regards
Thomas

**Comment by geerlingguy** [comment]
The Turing Pi gives you a pool of Pi servers. You can set it up in any way you want, with one master, three masters, or more. I just set mine up with one since HA on the control plane wasn't a design goal I had.

The K3s Ansible project has an HA setup PR in the works, too: https://github.com/k3s-io/k3s-ansible/pull/97
